### ISSUE TITLE
It dont work

### ISSUE THREAD

**Issue by M4xi2312** [DeathEnderMan/Nautical-Ranks#12]
if you join the Server it downloads the pack but it doesnt work so if i copy the symbols and paste them into the chat they still look like this ---> 
Server Software: PaperMC 1.20.2

**Comment by M4xi2312** [comment]
![image](https://github.com/user-attachments/assets/89b6e467-0ebb-49c3-8293-a439ae1d9738)

**Comment by jungltemple** [comment]
Are you sure the resource pack was downloaded? Sometimes I have a problem where the server resource pack is downloading but then it randomly fails.

Try testing it with the resource pack applied on your client - if that works then we know it's something to do with the download.
